name: Build docker image and deploy to wmd docker servers

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]
    
jobs:
    package:
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout
          uses: actions/checkout@v4
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: "seanglencrossitas"
            password: ${{secrets.DOCKER}}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        -
          name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: seanglencrossitas/itas276-nodegoat:latest
    
    deploy:
        name: "Deploy to ITAS WMD server"
        runs-on: itas276-sglencross
        needs: package
        steps:
            -   name: Docker pull
                run: |
                    mkdir ~/Assignment1
                    echo "TEST" > ~/Assignment1/test.txt
                    END
                #env:
                    #SSH_USER: ${{ vars.SSH_USER }}
                    #SSH_KEY: ${{ secrets.SSH_KEY }}
                    #SSH_HOST: ${{ vars.SSH_HOSTNAME }}
    
            -   name: Stop and remove docker container
                run: echo 'STOP DOCKER'
    
            -   name: Check out the source
                run: echo 'START DOCKER'
    